#!/usr/bin/python3

usage="""
scrape-statcode-us-co - convert the Colorado Revised Statutes into Akoma Ntoso

Get the data from <https://leg.colorado.gov/colorado-revised-statutes>.

Usage: scrape-statcode-us-co [options] zipfile dcl dtd
Arguments:
    zipfile     ZIP file containing the official CRS data
    dcl         SGML declaration
    dtd         SGML document type definition
    
    -t title    output specific titles (one flag for each)
    -o file     output file ('-' for stdout) (default: stdout)
    -n threads  maxmim number of parallel threads (default: 2)
    -d          enable debuging output (default: warnings only)
"""

import sys
import logging
import getopt
import os
import zipfile
import tempfile
import shutil
import subprocess
import bs4

##
# Entry function: Parse paramters, call main function.
#
def main():
    titles = []
    fout = sys.stdout.buffer
    threads = 2
    all_titles = list(str(n).zfill(2) for n in range(1,44))
    all_titles.append("25.5")
    all_titles.sort()

    # Configure logging.
    logging.basicConfig(format='{levelname} {process}/{threadName}: {message}', style='{', level=logging.WARNING)

    # Parse arguments.
    try:
        opts, args = getopt.gnu_getopt(sys.argv[1:], 'o:n:t:dh')
    except getopt.GetoptError:
        logging.fatal('Getopt error. {}'.format(usage))
        return 1

    for opt, arg in opts:
        if opt in {'-h', '--help'}:
            print(opt, usage)
            return 0
        elif opt in {'-d', '--debug'}:
            if logging.getLogger().level is logging.WARNING:
                logging.getLogger().setLevel(logging.INFO)
            elif logging.getLogger().level is logging.INFO:
                logging.getLogger().setLevel(logging.DEBUG)
        elif opt in {'-o'}:
            fout = arg
        elif opt in {'-n', '--threads'}:
            threads = int(arg)
        elif opt in {'-t', '--title'}:
            titles.append(arg.zfill(2))
        else:
            logging.fatal('Invalid flag \"{}\". {}'.format(opt, usage))
            return 1

    if len(args) < 3:
        logging.fatal('Need input files. {}'.format(usage))
        return 1
    zfn = os.path.abspath(args[0])
    dclfn = os.path.abspath(args[1])
    dtdfn = os.path.abspath(args[2])
    
    # Do all titles if none specified.
    if len(titles) == 0:
        titles = all_titles

	# Do it.
    return do_it(zfn, dclfn, dtdfn, titles, fout, threads)

##
# Do it.
#
def do_it(zfn, dclfn, dtdfn, titles, fout, threads): # Do it.
    with zipfile.ZipFile(zfn) as zf:
        for title in titles:
            # TODO: Convert each desired title in executors.
            logging.info('Converting title {}'.format(title))
            with zf.open('TITLES/title' + title + '.txt') as sgml:
                new_sgml = fix_sgml(sgml, dtdfn)
                xml = convert_sgml2xml(new_sgml, dclfn)
                akn = conv_xml2akn(xml)

##
# Given an official CRS SGML file, return a fixed SGML file. We need to
# add a DTD declaration, and fix various issues in the file.
#
# TODO: Run a diff against the file to fix various issues.
# XXX: Mind the newlines on different architectures!?
#
def fix_sgml(sgml, dtdfn):
    new_sgml = tempfile.NamedTemporaryFile()
    new_sgml.write(('<!DOCTYPE CRS SYSTEM "' + dtdfn + "\">\n").encode())
    shutil.copyfileobj(sgml, new_sgml)
    return new_sgml

##
# Convert a CRS SGML file file into XML.
#
# NOTE: Requires OpenSP.
#
def convert_sgml2xml(sgml, dclfn):
    xml = tempfile.NamedTemporaryFile(mode='w+')
    subprocess.run(["osx", dclfn, sgml.name], stdout=xml) # stderr=subprocess.DEVNULL
    xml.seek(0)
    return xml

##
# Convert a CRS SGML-as-XML file into Akoma Ntoso XML.
#
# XXX: TODO.
#
def conv_xml2akn(xml):
    soup = bs4.BeautifulSoup(xml, features="lxml")
    print(soup.prettify())

# <https://docs.python.org/3/library/__main__.html>
if __name__ == "__main__":
	main()

